baseURL = "https://tiramister.net/blog/"
languageCode = "ja"
defaultContentLanguage = "ja"
theme = "terminal"
title = "Tiramister's Blog"
enableGitInfo = true
hasCJKLanguage = true

[params]
themeColor = "green"
centerTheme = true
Toc = true
TocTitle = "ç›®æ¬¡"
showLastUpdated = true
readMore = "ç¶šãã‚’èª­ã‚€"

[params.logo]
logoText = "Tiramister's Blog"

[menu]
[[menu.main]]
identifier = "github"
name = "ğŸ› ï¸ GitHub"
url = "https://github.com/Tiramister/blog"
[[menu.main]]
identifier = "twitter"
name = "ğŸ’¬ Twitter"
url = "https://twitter.com/mistterpp"
