baseURL = "https://tiramister.net/blog/"
languageCode = "ja"
defaultContentLanguage = "ja"
theme = "terminal"
title = "Tiramister's Blog"
enableGitInfo = true
hasCJKLanguage = true

[params]
themeColor = "green"
centerTheme = true
favicon = "img/logo_red.png"
showLastUpdated = true

Toc = true
TocTitle = "目次"
readMore = "続きを読む"

[params.logo]
logoText = "Tiramister's Blog"

[menu]
[[menu.main]]
identifier = "algorithm"
name = "アルゴリズム・データ構造"
url = "/algorithm/"
